secretGenerator:
- name: mysql-root-pass
  literals:
  - password=R00t
- name: mysql-user-pass
  literals:
  - username=root
  - password=Wewin2021* 
- name: mysql-db-url
  literals:
  - database=polls
  - url=jdbc:mysql://polling-app-mysql:3306/polls?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
resources:
  - mysql-deployment.yaml
  - polling-app-server.yaml
  - polling-app-client.yaml  
