apiVersion: apps/v1             
kind: Deployment                
metadata:
  name: polling-app-client      
spec:
  replicas: 1                  
  selector:                     
    matchLabels:                
      app: polling-app-client
  template:                     
    metadata:
      labels:                   
        app: polling-app-client
    spec:                       
      containers:
      - name: polling-app-client
        image: viwin/polling-app-client:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 80   
        resources:
          limits:
            cpu: 0.2
            memory: "10Mi"
---
apiVersion: v1                  
kind: Service                   
metadata:
  name: polling-app-client      
spec:
  type: NodePort                
  selector:
    app: polling-app-client     
  ports:                       d
  - name: http
    port: 80
    targetPort: 80