apiVersion: apps/v1           
kind: Deployment              
metadata:
  name: polling-app-server    
  labels:                     
    app: polling-app-server
spec:
  replicas: 1                 
  selector:
    matchLabels:              
      app: polling-app-server
  template:                  
    metadata:
      labels:                
        app: polling-app-server
    spec:                     
      containers:
      - name: polling-app-server
        image: viwin/polling-app-server:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 8000 
        resources:
          limits:
            cpu: 0.2
            memory: "200Mi"
        env:                  
        - name: SPRING_DATASOURCE_USERNAME 
          valueFrom:          
            secretKeyRef:
              name: mysql-user-pass
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-user-pass
              key: password
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: mysql-db-url
              key: url
---
apiVersion: v1                
kind: Service                 
metadata:                     
  name: polling-app-server    
  labels:                     
    app: polling-app-server
spec:                         
  type: NodePort              
  selector:
    app: polling-app-server   
  ports:                      
  - name: http
    port: 8000
    targetPort: 8000
