

version: '3.7'

services:
  
  app-server:
    
    build:
      context: polling-app-server 
      dockerfile: Dockerfile
    ports:
      - "8000:8000" 
    restart: always
    depends_on: 
      - db .
    environment: 
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/polls?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: viwin
      SPRING_DATASOURCE_PASSWORD: viwin     
    networks: 
      - backend
      - frontend

 
  app-client:
    build:
      context: polling-app-client 
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: http://127.0.0.1:8000/api
    ports:
      - "9090:80" 
    restart: always
    depends_on:
      - app-server
    networks:
      - frontend  


  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: polls
      MYSQL_USER: root
      MYSQL_PASSWORD: Wewin2021*
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend  
  
volumes:
  db-data:

networks:
  backend:
  frontend:    